// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AniFade: typeof import('./../components/Animation/AniFade.vue')['default']
    BigScreen: typeof import('./../components/BigScreen.vue')['default']
    Card: typeof import('./../components/Card.vue')['default']
    CourseMetaCard: typeof import('./../components/Course/CourseMetaCard.vue')['default']
    CourseReviewCard: typeof import('./../components/Course/CourseReviewCard.vue')['default']
    ForumMetaCard: typeof import('./../components/Forum/ForumMetaCard.vue')['default']
    FullScreenCard: typeof import('./../components/Course/FullScreenCard.vue')['default']
    IconFold: typeof import('./../components/Icon/IconFold.vue')['default']
    IconStars: typeof import('./../components/Icon/IconStars.vue')['default']
    Input: typeof import('./../components/Input.vue')['default']
    IOcticonFilter16: typeof import('~icons/octicon/filter16')['default']
    IOcticonFold16: typeof import('~icons/octicon/fold16')['default']
    IOcticonLinkExternal: typeof import('~icons/octicon/link-external')['default']
    IOcticonStarFill16: typeof import('~icons/octicon/star-fill16')['default']
    IOcticonUnfold16: typeof import('~icons/octicon/unfold16')['default']
    Link: typeof import('./../components/Link.vue')['default']
    Nav: typeof import('./../components/Nav.vue')['default']
    SearchBar: typeof import('./../components/SearchBar.vue')['default']
    SoloForumArtical: typeof import('./../components/Forum/SoloForumArtical.vue')['default']
    Tag: typeof import('./../components/Tag.vue')['default']
  }
}

export { }
